### ISSUE TITLE
[gnomeshell-extension-manage] version detection broken on Fedora

### ISSUE THREAD

**Issue by eddy-geek** [NicolasBernaerts/ubuntu-scripts#13]
On Fedora (23 and 24), ``gnome-session --version`` (currently used by the script) prints nothing. To detect the gnome version I used instead:

    DISPLAY=":0" gnome-shell --version | cut -d' ' -f3 | cut -c1-4

This alternative should be cross-platform (to be checked on ubuntu-gnome)

**Comment by NicolasBernaerts** [comment]
Hi eddy-geek,
It should be solved with new V2.0 of the script.
Just let me know.

**Comment by eddy-geek** [comment]
Mmm I am not sure where is the V2, but the current master version is still broken...

    wget https://github.com/NicolasBernaerts/ubuntu-scripts/raw/master/ubuntugnome/gnomeshell-extension-manage
    chmod +x gnomeshell-extension-manage
    ./gnomeshell-extension-manage --install --extension-id 10

Prints

    Extension windowNavigator (Id 10) is not available for Gnome Shell version .

**Comment by NicolasBernaerts** [comment]
Hi,
The script only installs the exact extension version asked. 
So if your system version is not listed it won't install the extension.
To make it more flexible, I've updated the script to detect and install exact version or next available version.
It should now install extension even if your exact Gnome Shell version is not available.

**Comment by edgard** [comment]
Seems like gnome-session does not show version everywhere. On Ubuntu 16.04 for example, it's blank.  gnome-shell however replies with correct version. @eddy-geek fix works for me.

**Comment by NicolasBernaerts** [comment]
Script is using gnome-shell --version, so it should not be a problem.

Only problem if you work only with major and minor version (3.18) is that some extensions are released for a specific version (3.18.8). So, you may install the extension on a version which was not targeted.

Example : 
  Extension is available for 3.16, 3.18, 3.18.8. 
  You are running Gnome 3.18.2, you will install 3.18, you should install 3.18 : ok
  You are running Gnome 3.18.8, you will install 3.18, you should install 3.18.8 : nok

That's why I included a new mechanism to detect exact matching version or the first previously available.

**Comment by edgard** [comment]
Yup, you're right! Great stuff. Thanks for the fix!
